//Reference User Information
// export default {
//   "login": "john-smilga",
//   "id": 42133389,
//   "node_id": "MDQ6VXNlcjQyMTMzMzg5",
//   "avatar_url": "https://avatars.githubusercontent.com/u/42133389?v=4",
//   "gravatar_id": "",
//   "url": "https://api.github.com/users/john-smilga",
//   "html_url": "https://github.com/john-smilga",
//   "followers_url": "https://api.github.com/users/john-smilga/followers",
//   "following_url": "https://api.github.com/users/john-smilga/following{/other_user}",
//   "gists_url": "https://api.github.com/users/john-smilga/gists{/gist_id}",
//   "starred_url": "https://api.github.com/users/john-smilga/starred{/owner}{/repo}",
//   "subscriptions_url": "https://api.github.com/users/john-smilga/subscriptions",
//   "organizations_url": "https://api.github.com/users/john-smilga/orgs",
//   "repos_url": "https://api.github.com/users/john-smilga/repos",
//   "events_url": "https://api.github.com/users/john-smilga/events{/privacy}",
//   "received_events_url": "https://api.github.com/users/john-smilga/received_events",
//   "type": "User",
//   "site_admin": false,
//   "name": "John Smilga",
//   "company": "Coding Addict",
//   "blog": "www.johnsmilga.com",
//   "location": "Los Angeles",
//   "email": null,
//   "hireable": null,
//   "bio": "Creator of Coding Addict",
//   "twitter_username": "john_smilga",
//   "public_repos": 214,
//   "public_gists": 0,
//   "followers": 5592,
//   "following": 0,
//   "created_at": "2018-08-06T06:48:23Z",
//   "updated_at": "2021-05-19T16:44:20Z"
// }

export default {
  "login": "Brennan-W-Curtis",
  "id": 62488561,
  "node_id": "MDQ6VXNlcjYyNDg4NTYx",
  "avatar_url": "https://avatars.githubusercontent.com/u/62488561?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Brennan-W-Curtis",
  "html_url": "https://github.com/Brennan-W-Curtis",
  "followers_url": "https://api.github.com/users/Brennan-W-Curtis/followers",
  "following_url": "https://api.github.com/users/Brennan-W-Curtis/following{/other_user}",
  "gists_url": "https://api.github.com/users/Brennan-W-Curtis/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Brennan-W-Curtis/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Brennan-W-Curtis/subscriptions",
  "organizations_url": "https://api.github.com/users/Brennan-W-Curtis/orgs",
  "repos_url": "https://api.github.com/users/Brennan-W-Curtis/repos",
  "events_url": "https://api.github.com/users/Brennan-W-Curtis/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Brennan-W-Curtis/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Brennan Curtis",
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 5,
  "public_gists": 0,
  "followers": 0,
  "following": 5,
  "created_at": "2020-03-21T23:51:37Z",
  "updated_at": "2021-04-29T14:01:49Z"
}
